services:
  - type: web
    name: mailblast-omega
    env: python
    buildCommand: "pip install -r requirements.txt && chmod +x start.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
